version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpass
      POSTGRES_DB: stockdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://stockuser:stockpass@db:5432/stockdb
    depends_on:
      - db

volumes:
  pgdata: